name: CI/CD Pipeline

on:
  push:
    branches: [develop, feature/*, hotfix/*]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Display .NET version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore **/*.sln

      - name: Build solution
        run: dotnet build **/*.sln --no-restore --configuration Release

      - name: Run tests
        run: |
          TEST_PROJECTS=$(find . -name "*Test*.csproj" -o -name "*.Test.csproj" -o -name "*.Tests.csproj")
          if [ -n "$TEST_PROJECTS" ]; then
            for proj in $TEST_PROJECTS; do
              dotnet test "$proj" --no-build --configuration Release \
                --logger trx --results-directory TestResults
            done
          else
            echo "No test projects found. Skipping tests."
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: TestResults/*.trx

  code-quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore **/*.sln

      - name: Run code analysis
        run: |
          if find . -name "*.csproj" -print -quit | grep -q .; then
            dotnet build **/*.sln --configuration Release --verbosity normal
            echo "Code analysis completed successfully"
          else
            echo "No .NET projects found for code analysis."
          fi
